### PR TITLE
A YouTube Video Page Clone - Built with HTML & CSS

### PR DESCRIPTION
**Pull request by CalyCherkaoui**
We created a Youtube Video Page following the instructions required by [The Odin Project](https://www.theodinproject.com/courses/html5-and-css3/lessons/embedding-images-and-video) and [Microverse Curriculum ](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/).

Any new changes will be documented and pushed on this pull request.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Great work so far :+1: 

#### In future projects I am asking you not to close pull request after first review. You can make commits and submit new review requests using same pull request.

Here are changes you need to make, before this project can be approved:

* [ ] check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.
* [ ] Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [ ] `share` should be a button, right now it's image ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
* [ ] It's better to add some space between images and text. Right now they look not very good:
image
* [ ] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) You have a lot of commented code, that should be removed.
* [ ] No inline styling. You have a lot of styling in your `index.html` file, please move everything to `Style.css`.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by idgm5** [comment]
We have a problem with indentations. 

I tried with automate fix using sticker-ci in local and look for extra spaces. Also using 2 Tabs instead of 2 spaces even 4 spaces and trying to keep all the code inline (as you can see in the commits) but we still have the same errors with indentations.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi team, you are almost there. But we need to fix these:**
1. The sidebar does not look like the original one.
**Yours:**
image

**Original:**
image

2. We need to have the stickler test passing before approval. Check your editor indentation setting and make sure it is set to 2 spaces. That should enable you correct the indentation in the code.

**_Please fix the above and submit for another review_**

**Cheers:stars:**

**Comment by idgm5** [comment]
@mosesogwo Can you help us with some info about the browser are you using and in which resolution? 

We didn't have any problem with the sidebar with other the other reviewers, I believe this could be a unique problem with the setup.

**Comment by mosesogwo** [comment]
Hello @ghamtre, I'm sorry if this problem was only happening on my own end. In that case, kindly submit another code review request and another TSE will look at it but not before the stickler errors are taken care of.

Thanks.

**Comment by uryelah** [comment]
### Pull Request under the review by Sarah Uryelah Silva Chamorro (TSE)

**Comment by uryelah** [comment]
Hello **Houda Cherkaoui** & **Isaac Gonzalez Munguia**, I'm Sarah, your reviewer for this PR .

You did a great job completing the two required changes from the last review, congrats! 🥇 

**Great job at:**
- **Finishing your first Microverse project**
- linting your project
- adding `:hover` and `:focus` effects on CSS
- adding `cursor: pointer` to the main video
- great README.md file

### Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

**Optional changes (That I know you'll make because you have displayed incredible CSS skills!)**

### (Even) Better CSS

- [ ]  [OPTIONAL] You already added `cursor: pointer` to your share button and vide, so why not also add it for nav icons, channel name, save... [Check on youtube which elements are clickable for reference.](https://www.youtube.com/watch?v=V74l_zS1x8E)

- [ ]  [OPTIONAL] Sometimes the CSS cascade can be frustrating, but try to avoid using too many `!important`. Check out[ this article ](https://uxengineer.com/css-specificity-avoid-important-css/)on the subject.
 
- [ ]  [OPTIONAL] The original page links are grey
youtube share button
while yours are the default blue color. How about styling them to a similar gray? 
[(check this if you get stuck)](https://www.w3schools.com/Css/css_link.asp)

-  [ ]  [OPTIONAL] Make your page more semantic, the div with the class `videoSection` is the main focus of the page, so why not [use a `<main>` tag](https://www.w3schools.com/tags/tag_main.asp)?


-------

**Congrats on your journey in Microverse and Good Luck in your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
